### ISSUE TITLE
Zopar tipov

### ISSUE THREAD

**Issue by miro-janosik** [pisk-cz/checklist#1]
- odporucate nepouzivat Win10 ale nepopisete vhodne alternativy. Co odporucate, Linux, Ubuntu? Alebo iba Mac?
- odporucate nepouzivat Win10 ale pri zalohovani, sifrovani pisete navod na Win a Mac, nie na Ubuntu alebo ine
- ku Thunderbird pridajte informaciu pre tych ktori sa musia pripajat na pracovny Exchange e-mail ucet a potrebuju pouzivat kalendar a kontakty, ze existuje (platene 10e rocne) rozsirenie ExQuilla, kedze Exchange je dost rozsireny v zamestnaniach
- WhatsApp PIN link nefunguje, mozno zmenit na https://faq.whatsapp.com/general/verification/how-to-manage-two-step-verification-settings

**Comment by good-lly** [comment]
- nepouzivanie sa tam dostalo mojim nedopatrenim (dali sme to prec)
- dobra poznamka, zalohovanie linuxu spominal @ruzaq v https://github.com/pisk-cz/checklist/issues/2 ... uvidime ci posle pull request, pripadne mozes navrhnut ty :) to iste aj u Thunderbirdu ... velmi rad urobim review/schvalenie 🙏 

@miro-janosik prepac ze to tolko trva

**Comment by miro-janosik** [comment]
Vacsinu ste uz zapracovali, tak som spravil iba maly pull-request #4
